access_points: [changeap]
transport_config:
  allow_insecure: true
provider: ofi+tcp;ofi_rxm
disable_vfio: true
crt_timeout: 200

engines:
-
   targets: 8
   nr_xs_helpers: 0
   first_core: 1
   fabric_iface_port: 31316
   fabric_iface: eth0
   log_mask: ERR
   log_file: /var/daos/engine.log

   env_vars:
      - FI_OFI_RXM_DEF_TCP_WAIT_OBJ=pollfd

   scm_mount: /var/daos/ram
   scm_class: ram
   scm_size: 100

   bdev_class: nvme
   bdev_list: ["0000:00:04.0"]
